### ISSUE TITLE
Implement content iterators

### ISSUE THREAD

**Issue by vmadman** [Dasix/grits#13]
**Note:** This issue is part of my early to-do list and may or may not be added.  I simply wanted to move my paper check list into something a bit more permanent and formal.
#### Summary

It should be possible to allow a single content file to generate multiple output files in a systematic way.

I have not thought this through very well at this point, but one way this might be done is through front-matter variables that allow pages to be generated based on either in-line front-matter data or the data from data files.

**Data File Example**

``` yaml

---
iterate:
  on: data.whatever
  name: page-?-x.md

---
```

**In-line Example**

``` yaml

---
stuff:
  - apples
  - oranges
iterate:
  on: stuff
  name: page-?-x.md

---
```

(or `_page.stuff` or `_self.stuff`, etc etc)
